apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  project: travel-guide-project
  source:
    repoURL: 'https://github.com/ceztro/ArgoCD_GitOps.git'
    targetRevision: dev
    path: argocd_applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true