apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    v1/ConfigMap:
      ignoreDifferences: |
        jsonPointers:
        - /data/mapRoles
        - /data/mapUsers