apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::871548798187:role/bastion-host-role
      username: admin
      groups:
        - read-only